"""Initial migration

Revision ID: 1
Revises: 
Create Date: 2021-08-05 15:50:44.556778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("value", sa.String(length=90), nullable=False),
        sa.Column("testnet", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("value"),
    )
    op.create_index(
        op.f("ix_addresses_testnet"), "addresses", ["testnet"], unique=False
    )
    op.create_table(
        "lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lists_name"), "lists", ["name"], unique=True)
    op.create_table(
        "address_listings",
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("address_value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_value"],
            ["addresses.value"],
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.id"],
        ),
        sa.PrimaryKeyConstraint("list_id", "address_value"),
    )
    op.create_index(
        "ix_address_listings_list_id_address_value",
        "address_listings",
        ["list_id", "address_value"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_address_listings_list_id_address_value", table_name="address_listings"
    )
    op.drop_table("address_listings")
    op.drop_index(op.f("ix_lists_name"), table_name="lists")
    op.drop_table("lists")
    op.drop_index(op.f("ix_addresses_testnet"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
